# Aliases
alias ls='eza -T -L 1 --group-directories-first --links --smart-group --changed --icons'
alias vim='nvim'
alias neovim='nvim'
alias c='clear'
alias lzd='lazydocker'
alias lzg='lazygit'
alias back='cd $HOME/FRETE-E-API/ && source venv/bin/activate && python3 manage.py runserver'
alias front='cd $HOME/FRETE-E-FED/ && git switch develop && git pull && npm i && npm run dev'
alias data='cd $HOME/agro-data/ && source venv/bin/activate && fastapi dev app/main.py --port 8001 --reload'
alias 'cd..'='cd ..'
alias dc='docker compose'
